# ec2-instance.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: crossplane-lab-ec2
spec:
  forProvider:
    region: us-east-1
    instanceType: t2.micro
    ami: ami-0c02fb55956c7d316 # Amazon Linux 2 AMI (us-east-1)
    keyName: crossplane-lab-keypair # Nombre del par de claves (debe existir en AWS)
    subnetIdRef:
      name: crossplane-lab-subnet # Referencia al recurso Subnet creado previamente
    tags:
      Name: "crossplane-lab-ec2"
  providerConfigRef:
    name: default