# provider-aws.yaml (Versión actualizada y correcta)
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  # Puedes cambiar el nombre si quieres, o dejarlo así
  name: provider-aws
spec:
  # Usamos el provider que contiene EC2, S3, RDS, etc.
  package: xpkg.upbound.io/upbound/provider-aws:v1.4.0